# Generated by Django 4.2.23 on 2025-08-20 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdlTest',
        ),
    ]
